# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.FileField(max_length=250, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produit',
            name='logo',
            field=models.ImageField(upload_to='image/media/ali/boutique_name/product_images_date_ajout'),
        ),
    ]
