# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import produit.models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_auto_20170628_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='logo',
            field=models.ImageField(upload_to=produit.models.group_based_upload_to),
        ),
    ]
