# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_auto_20170629_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('active', 'active'), ('desactive', 'desactive')], default='active', max_length=250),
        ),
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
