# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import produit.models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_auto_20170629_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='logo1',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder),
        ),
        migrations.AddField(
            model_name='produit',
            name='logo2',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder),
        ),
        migrations.AddField(
            model_name='produit',
            name='logo3',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder),
        ),
    ]
