# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import produit.models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_auto_20170630_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AddField(
            model_name='produit',
            name='image1',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder),
        ),
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder),
        ),
        migrations.AddField(
            model_name='produit',
            name='image3',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder),
        ),
        migrations.AlterField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('active', 'active'), ('desactive', 'desactive')], default='desactive', max_length=250),
        ),
    ]
