# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_auto_20170630_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
